AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active

Resources:
  ################################################################################
  # Resources for sending new messages
  ################################################################################
  SendMessageStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/SendMessage.asl.yaml
      DefinitionSubstitutions:
        SendMessageFunctionArn: !GetAtt SendMessageFunction.Arn
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-statemachineapi.html
          Properties:
            Method: post
            Path: /chats/{chatId}/messages
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref SendMessageFunction

  SendMessageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/sendMessage/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64

  ################################################################################
  # Resources for retrieving and translating messages
  ################################################################################
  GetNewMessagesStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/GetNewMessages.asl.yaml
      DefinitionSubstitutions:
        GetNewMessagesFunctionArn: !GetAtt GetNewMessagesFunction.Arn
        StoreTranslatedMessageFunctionArn: !GetAtt StoreTranslatedMessage.Arn
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-statemachineapi.html
          Properties:
            Method: get
            Path: /chats/{chatId}/messages
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref GetNewMessagesFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StoreTranslatedMessage

  GetNewMessagesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/getNewMessages/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64

  StoreTranslatedMessageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/storTranslatedMessage/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64

Outputs:
  SendMessageStateMachineArn:
    Description: "Send Message state machine ARN"
    Value: !Ref SendMessageStateMachine

  GetNewMessagesStateMachineArn:
    Description: "Get New Messages state machine ARN"
    Value: !Ref GetNewMessagesStateMachine

  # When the Event property of an AWS::Serverless::Function is set to Api, but the RestApiId property is not specified, AWS SAM generates the AWS::ApiGateway::RestApi AWS CloudFormation resource.
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources-function.html#sam-specification-generated-resources-function-api
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
