# Copyright Fauna, Inc.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Parameters:
  FaunaDomain:
    Type: String
    Description: >
      Enter the domain name to access Fauna. 

      As of 28 June 2022 valid production domains are:
        * `db.us.fauna.com` (US Region Group)
        * `db.eu.fauna.com` (EU Region Group)
        * `db.fauna.com` (Classic Region Group)
    Default: db.fauna.com

  FaunaServerKey:
    Type: String
    Description: >
      A key assigned to the "server" role for accessing Fauna.
    NoEcho: true
    AllowedPattern: "^fnA[a-zA-Z0-9+=_-]{37}$"

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active
    Environment:
      Variables:
        FAUNA_DOMAIN:
          Ref: FaunaDomain
        FAUNA_API_KEY:
          Ref: FaunaServerKey

Resources:
  ################################################################################
  # HTTP API and associated role for invoking Step Functions workflows
  ################################################################################
  HttpApiForSynchronousWorkflows:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: openapi.yaml

  HttpApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
      - PolicyName: AllowSFNExec
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "states:StartSyncExecution"
              Resource: !GetAtt SendMessageStateMachine.Arn
            - Effect: Allow
              Action: "states:StartSyncExecution"
              Resource: !GetAtt GetNewMessagesStateMachine.Arn

  ################################################################################
  # Resources for sending new messages
  ################################################################################
  SendMessageStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      Type: EXPRESS
      Tracing: 
        Enabled: true
      DefinitionUri: statemachine/SendMessage.asl.yaml
      DefinitionSubstitutions:
        SendMessageFunctionArn: !GetAtt SendMessageFunction.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref SendMessageFunction

  SendMessageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/
      Handler: app.sendMessage
      Runtime: nodejs16.x
      Architectures:
        - x86_64

  ################################################################################
  # Resources for retrieving and translating messages
  ################################################################################
  GetNewMessagesStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      Type: EXPRESS
      Tracing: 
        Enabled: true
      DefinitionUri: statemachine/GetNewMessages.asl.yaml
      DefinitionSubstitutions:
        GetNewMessagesFunctionArn: !GetAtt GetNewMessagesFunction.Arn
        StoreTranslatedMessageFunctionArn: !GetAtt StoreTranslatedMessageFunction.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref GetNewMessagesFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StoreTranslatedMessageFunction
        - arn:aws:iam::aws:policy/TranslateReadOnly

  GetNewMessagesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/
      Handler: app.getNewMessages
      Runtime: nodejs16.x
      Architectures:
        - x86_64

  StoreTranslatedMessageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/
      Handler: app.storeTranslatedMessage
      Runtime: nodejs16.x
      Architectures:
        - x86_64

Outputs:
  SendMessageStateMachineArn:
    Description: "Send Message state machine ARN"
    Value: !Ref SendMessageStateMachine

  GetNewMessagesStateMachineArn:
    Description: "Get New Messages state machine ARN"
    Value: !Ref GetNewMessagesStateMachine

  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub https://${HttpApiForSynchronousWorkflows}.execute-api.${AWS::Region}.amazonaws.com
